# Generated by Django 4.2.5 on 2023-10-05 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='p_img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
