# Generated by Django 4.2.6 on 2023-11-09 03:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_cart_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='user/person.png', upload_to='user/'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 9, 3, 43, 29, 870307, tzinfo=datetime.timezone.utc)),
        ),
    ]
