# Generated by Django 4.2.6 on 2023-11-21 04:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_transaction_trans_id_alter_cart_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 21, 4, 42, 27, 55774, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 11, 21, 4, 42, 27, 55774, tzinfo=datetime.timezone.utc)),
        ),
    ]
