from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('about/',views.about,name='about'),
    path('contact/',views.contact,name='contact'),
    path('signup/',views.signup,name='signup'),
    path('login/',views.login,name='login'),
    path('logout/',views.logout,name='logout'),
    path('fpswd/',views.fpswd,name='fpswd'),
    path('verify_otp/',views.verify_otp,name='verify_otp'),
    path('create_new_pswd/', views.create_new_pswd, name='create_new_pswd'),
    path('farmer_index/',views.farmer_index,name='farmer_index'),
    path('add_product/',views.add_product,name='add_product'),
    path('update_product/<int:pk>',views.update_product,name='update_product'),
    path('remove_product/<int:pk>',views.remove_product,name='remove_product'),
    path('products/',views.products,name='products'),
    path('product_details/<int:pk>',views.product_details,name='product_details'),
    path('filter/<int:pk>',views.filter,name='filter'),
    path('create_blog/',views.create_blog,name='create_blog'),
    path('my_blog/',views.my_blog,name='my_blog'),
    path('all_products_customer/',views.all_products_customer,name='all_products_customer'),
    path('product_detail_customer/<int:pk>',views.product_detail_customer,name='product_detail_customer'),
    path('add_to_wishlist/<int:pk>',views.add_to_wishlist,name='add_to_wishlist'),
    path('wishlist/',views.wishlist,name='wishlist'),
    path('remove_from_wishlist/<int:pk>',views.remove_from_wishlist,name='remove_from_wishlist'),
    path('add_to_cart/<int:pk>',views.add_to_cart,name='add_to_cart'),
    path('cart/',views.cart,name='cart'),
    path('change_qty/<int:pk>/',views.change_qty,name='change_qty'),
    path('remove_from_cart/<int:pk>',views.remove_from_cart,name='remove_from_cart'),
    path('customer_show_blog',views.customer_show_blog,name='customer_show_blog'),
    path('read_blog_unique/<int:pk>',views.read_blog_unique,name='read_blog_unique'),
    path('c_dashboard',views.c_dashboard,name='c_dashboard'),
    path('c_dash_header',views.c_dash_header,name='c_dash_header'),
    path('c_dash_profile/',views.c_dash_profile,name='c_dash_profile'),
    path('cart/success',views.success,name='success'),
    path('d_cart/',views.d_cart,name='d_cart'),
    path('rd_cart/<int:pk>/',views.rd_cart,name='rd_cart'),
    path('order_history/',views.order_history,name='order_history'),
]
